apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-vgpu-lab
spec:
  selector:
    matchLabels:
      app: mnist-vgpu-lab
  replicas: 2
  template:
    metadata:
      labels:
        app: mnist-vgpu-lab
    spec:
      containers:
        - name: mnist
          image: chph/mnist:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8051
          resources:
            limits:
              transwarp.io/vgpu-core: 50
              transwarp.io/vgpu-memory: 7

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mnist-vgpu-lab
  name: mnist-vgpu-lab
spec:
  ports:
    - port: 8051
      targetPort: 8051
      nodePort: 31500
  selector:
    app: mnist-vgpu-lab
  type: NodePort
