apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-vgpu-lab
spec:
  selector:
    matchLabels:
      app: mnist-vgpu-lab
  replicas: 1
  template:
    metadata:
      labels:
        app: mnist-vgpu-lab
    spec:
      containers:
        - name: mnist
          image: chph/mnist:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mnist-vgpu-lab
  name: mnist-vgpu-lab
spec:
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 31500
  selector:
    app: mnist-vgpu-lab
  type: NodePort
