apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifar10-vgpu-lab
spec:
  selector:
    matchLabels:
      app: cifar10-vgpu-lab
  replicas: 1
  template:
    metadata:
      labels:
        app: cifar10-vgpu-lab
    spec:
      containers:
        - name: cifar10
          image: chph/cifar-10:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cifar10-vgpu-lab
  name: cifar10-vgpu-lab
spec:
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 31000
  selector:
    app: cifar10-vgpu-lab
  type: NodePort
