apiVersion: apps/v1
kind: Deployment
metadata:
  name: vgpu-utilization-server
spec:
  selector:
    matchLabels:
      app: vgpu-utilization-server
  replicas: 1
  template:
    metadata:
      labels:
        app: vgpu-utilization-server
    spec:
      containers:
        - name: utilization-server
          image: chph/utilization-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8051

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: vgpu-utilization-server
  name: vgpu-utilization-server
spec:
  ports:
    - port: 8051
      targetPort: 8051
      nodePort: 31300
  selector:
    app: vgpu-utilization-server
  type: NodePort
